name: Trigger Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Build
        run: docker build . -t ghcr.io/josephduffy/docc-nginx:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        run: docker push ghcr.io/josephduffy/docc-nginx:latest

  trigger_update:
    name: Trigger Update
    needs:
      - build_image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Simulate Webhook
        run: ./scripts/trigger-update-webhook.sh docc-nginx "${{ secrets.UPDATE_CONTAINER_SECRET }}" "${{ secrets.UPDATE_CONTAINERS_HOOK_URL }}"
